[book]
title = "魂孪英旅 下 魔齿磨轮"
authors = ["COCOVS"]
language = "zh"
multilingual = false
src = "src"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
no-section-label = true
site-url = "/Essence-polarity/book2/"

[output.html.playground]
editable = true

[output.html.search]
enable = true
