[book]
title = "《魂孪英旅 上 地上星》"
authors = ["Linyu霖"]
language = "zh"
multilingual = false
src = "src"

[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
no-section-label = true

[output.html.playground]
editable = true

[output.html.search]
enable = true
